config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :abcs
  resources :seihinns
  resources :product3s
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/abc.rb
class Abc < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/product3.rb
class Product3 < ApplicationRecord
end

app/models/seihinn.rb
class Seihinn < ApplicationRecord
end

app/controllers/abcs_controller.rb
class AbcsController < ApplicationController
  before_action :set_abc, only: %i[ show edit update destroy ]

  # GET /abcs or /abcs.json
  def index
    @abcs = Abc.all
  end

  # GET /abcs/1 or /abcs/1.json
  def show
  end

  # GET /abcs/new
  def new
    @abc = Abc.new
  end

  # GET /abcs/1/edit
  def edit
  end

  # POST /abcs or /abcs.json
  def create
    @abc = Abc.new(abc_params)

    respond_to do |format|
      if @abc.save
        format.html { redirect_to @abc, notice: "Abc was successfully created." }
        format.json { render :show, status: :created, location: @abc }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @abc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abcs/1 or /abcs/1.json
  def update
    respond_to do |format|
      if @abc.update(abc_params)
        format.html { redirect_to @abc, notice: "Abc was successfully updated." }
        format.json { render :show, status: :ok, location: @abc }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @abc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abcs/1 or /abcs/1.json
  def destroy
    @abc.destroy
    respond_to do |format|
      format.html { redirect_to abcs_url, notice: "Abc was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abc
      @abc = Abc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def abc_params
      params.require(:abc).permit(:name, :price, :vendor)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/product3s_controller.rb
class Product3sController < ApplicationController
  before_action :set_product3, only: %i[ show edit update destroy ]

  # GET /product3s or /product3s.json
  def index
    @product3s = Product3.all
  end

  # GET /product3s/1 or /product3s/1.json
  def show
  end

  # GET /product3s/new
  def new
    @product3 = Product3.new
  end

  # GET /product3s/1/edit
  def edit
  end

  # POST /product3s or /product3s.json
  def create
    @product3 = Product3.new(product3_params)

    respond_to do |format|
      if @product3.save
        format.html { redirect_to @product3, notice: "Product3 was successfully created." }
        format.json { render :show, status: :created, location: @product3 }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product3.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product3s/1 or /product3s/1.json
  def update
    respond_to do |format|
      if @product3.update(product3_params)
        format.html { redirect_to @product3, notice: "Product3 was successfully updated." }
        format.json { render :show, status: :ok, location: @product3 }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product3.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product3s/1 or /product3s/1.json
  def destroy
    @product3.destroy
    respond_to do |format|
      format.html { redirect_to product3s_url, notice: "Product3 was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product3
      @product3 = Product3.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product3_params
      params.require(:product3).permit(:name, :price, :vendor)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :vendor)
    end
end

app/controllers/seihinns_controller.rb
class SeihinnsController < ApplicationController
  before_action :set_seihinn, only: %i[ show edit update destroy ]

  # GET /seihinns or /seihinns.json
  def index
    @seihinns = Seihinn.all
  end

  # GET /seihinns/1 or /seihinns/1.json
  def show
  end

  # GET /seihinns/new
  def new
    @seihinn = Seihinn.new
  end

  # GET /seihinns/1/edit
  def edit
  end

  # POST /seihinns or /seihinns.json
  def create
    @seihinn = Seihinn.new(seihinn_params)

    respond_to do |format|
      if @seihinn.save
        format.html { redirect_to @seihinn, notice: "Seihinn was successfully created." }
        format.json { render :show, status: :created, location: @seihinn }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @seihinn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seihinns/1 or /seihinns/1.json
  def update
    respond_to do |format|
      if @seihinn.update(seihinn_params)
        format.html { redirect_to @seihinn, notice: "Seihinn was successfully updated." }
        format.json { render :show, status: :ok, location: @seihinn }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @seihinn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seihinns/1 or /seihinns/1.json
  def destroy
    @seihinn.destroy
    respond_to do |format|
      format.html { redirect_to seihinns_url, notice: "Seihinn was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seihinn
      @seihinn = Seihinn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def seihinn_params
      params.require(:seihinn).permit(:name, :price, :vendor)
    end
end

app/helpers/abcs_helper.rb
module AbcsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product3s_helper.rb
module Product3sHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/seihinns_helper.rb
module SeihinnsHelper
end

app/views/abcs/_form.html.erb
<%= form_with(model: abc, local: true) do |form| %>
  <% if abc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(abc.errors.count, "error") %> prohibited this abc from being saved:</h2>

      <ul>
      <% abc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :vendor %>
    <%= form.text_field :vendor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/abcs/edit.html.erb
<h1>Editing Abc</h1>

<%= render 'form', abc: @abc %>

<%= link_to 'Show', @abc %> |
<%= link_to 'Back', abcs_path %>

app/views/abcs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Abcs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Vendor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @abcs.each do |abc| %>
      <tr>
        <td><%= abc.name %></td>
        <td><%= abc.price %></td>
        <td><%= abc.vendor %></td>
        <td><%= link_to 'Show', abc %></td>
        <td><%= link_to 'Edit', edit_abc_path(abc) %></td>
        <td><%= link_to 'Destroy', abc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Abc', new_abc_path %>

app/views/abcs/new.html.erb
<h1>New Abc</h1>

<%= render 'form', abc: @abc %>

<%= link_to 'Back', abcs_path %>

app/views/abcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @abc.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @abc.price %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @abc.vendor %>
</p>

<%= link_to 'Edit', edit_abc_path(@abc) %> |
<%= link_to 'Back', abcs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductRegister</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product3s/_form.html.erb
<%= form_with(model: product3, local: true) do |form| %>
  <% if product3.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product3.errors.count, "error") %> prohibited this product3 from being saved:</h2>

      <ul>
      <% product3.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :vendor %>
    <%= form.text_field :vendor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product3s/edit.html.erb
<h1>Editing Product3</h1>

<%= render 'form', product3: @product3 %>

<%= link_to 'Show', @product3 %> |
<%= link_to 'Back', product3s_path %>

app/views/product3s/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product3s</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Vendor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product3s.each do |product3| %>
      <tr>
        <td><%= product3.name %></td>
        <td><%= product3.price %></td>
        <td><%= product3.vendor %></td>
        <td><%= link_to 'Show', product3 %></td>
        <td><%= link_to 'Edit', edit_product3_path(product3) %></td>
        <td><%= link_to 'Destroy', product3, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product3', new_product3_path %>

app/views/product3s/new.html.erb
<h1>New Product3</h1>

<%= render 'form', product3: @product3 %>

<%= link_to 'Back', product3s_path %>

app/views/product3s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product3.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product3.price %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @product3.vendor %>
</p>

<%= link_to 'Edit', edit_product3_path(@product3) %> |
<%= link_to 'Back', product3s_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :vendor %>
    <%= form.text_field :vendor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Vendor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.vendor %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @product.vendor %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/seihinns/_form.html.erb
<%= form_with(model: seihinn, local: true) do |form| %>
  <% if seihinn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seihinn.errors.count, "error") %> prohibited this seihinn from being saved:</h2>

      <ul>
      <% seihinn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :vendor %>
    <%= form.text_field :vendor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seihinns/edit.html.erb
<h1>Editing Seihinn</h1>

<%= render 'form', seihinn: @seihinn %>

<%= link_to 'Show', @seihinn %> |
<%= link_to 'Back', seihinns_path %>

app/views/seihinns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seihinns</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Vendor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seihinns.each do |seihinn| %>
      <tr>
        <td><%= seihinn.name %></td>
        <td><%= seihinn.price %></td>
        <td><%= seihinn.vendor %></td>
        <td><%= link_to 'Show', seihinn %></td>
        <td><%= link_to 'Edit', edit_seihinn_path(seihinn) %></td>
        <td><%= link_to 'Destroy', seihinn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seihinn', new_seihinn_path %>

app/views/seihinns/new.html.erb
<h1>New Seihinn</h1>

<%= render 'form', seihinn: @seihinn %>

<%= link_to 'Back', seihinns_path %>

app/views/seihinns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @seihinn.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @seihinn.price %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @seihinn.vendor %>
</p>

<%= link_to 'Edit', edit_seihinn_path(@seihinn) %> |
<%= link_to 'Back', seihinns_path %>